site_name: Instructed Glacier Model (IGM)
site_url: https://jouvetg.github.io/igm-doc.github.io/
site_description: >-
  Run your own glacier simulations in a fast, accurate, and user-friendly way.

# Repository
repo_name: jouvetg/igm
repo_url: https://github.com/jouvetg/igm

nav:
  - Home: index.md
  - Installation:
      - Quick Start: installation/quick_start.md
      - Other:
        - Nvidia Drivers: installation/other/nvidia_drivers.md
        - Virtual Environments: installation/other/virtual_environment.md
        - WSL Windows: installation/other/wsl_windows.md
      # - Linux: installation/linux.md
      # - Windows: installation/windows.md
      # - MacOS: installation/mac.md
      # - Docker: Installation_Docker.md
  - Getting Started:
      - Using Hydra:
        - Introduction: hydra/introduction.md
        - Configuration: hydra/configuration.md
        - Distributed Computing: hydra/distributed_computing.md
      
      - Examples: examples/Examples.md
#        - Quick Demo: examples/quick_demo.md
#        - Aletsch Basic: examples/aletsch_basic.md
  # - Running IGM: Running.md
  - Modules:
    - What are modules?: modules/introduction.md
    - Input:
      - local: modules/inputs/local.md
      - load_ncdf: modules/inputs/load_ncdf.md
      - load_tif: modules/inputs/load_tif.md
      - oggm_shop: modules/inputs/oggm_shop.md
    - Processes:
      - avalanche: modules/processes/avalanche.md
      - clim_glacialindex: modules/processes/clim_glacialindex.md
      - clim_oggm: modules/processes/clim_oggm.md
      - enthalpy: modules/processes/enthalpy.md
      - gflex: modules/processes/gflex.md
      - glerosion: modules/processes/glerosion.md
      - iceflow: modules/processes/iceflow.md
      - particles: modules/processes/particles.md
      - read_output: modules/processes/read_output.md
      - rockflow: modules/processes/rockflow.md
      - smb_accpdd: modules/processes/smb_accpdd.md
      - smb_oggm: modules/processes/smb_oggm.md
      - smb_simple: modules/processes/smb_simple.md
      - texture: modules/processes/texture.md
      - thk: modules/processes/thk.md
      - time: modules/processes/time.md
      - vert_flow: modules/processes/vert_flow.md
    - Output:
      - local: modules/outputs/local.md
      - write_ncdf: modules/outputs/write_ncdf.md
      - write_tif: modules/outputs/write_tif.md
      - write_ts: modules/outputs/write_ts.md
      - plot2d: modules/outputs/plot2d.md
    - User: about/user_modules.md

  # - Gallery:
  #     - Gallery: gallery/gallery.md
  - About:
      # - About IGM: about/about.md
      - Transitioning from IGM 2 to 3: about/transition-IGM-2-to-3.md
      - Graphical Processing Units (GPUs): about/gpus.md
      - Tensorflow: about/tensorflow.md
      - Crediting IGM: about/credits_and_references.md
      - Variables: about/variables.md
      # - FAQ: about/FAQ.md

plugins:
  - search
  - include-markdown
  - macros:
      # include_yaml:
        # - igm/igm/conf/modules/avalanche.yaml
        # - igm/igm/conf_help/modules/avalanche.yaml
        # - avalanche: igm/igm/conf/modules/avalanche.yaml
        # - avalanche_help: igm/igm/conf_help/modules/avalanche.yaml
      include_dir: ./igm/igm/
      # render_by_default: false
  - table-reader

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

theme:
  name: material
  custom_dir: docs/material/overrides
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    - scheme: glacier_light
      # primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for light mode
    - scheme: glacier_dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Inter
    # code: PragmataPro
    code: Fira Code

  language: en
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

    - navigation.path
    - navigation.instant.progress
    - navigation.tabs
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.suggest

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  # yaml_data: !include_dir 'igm/igm/conf/modules'
  # unit_price: 10
  # social:
  #   - icon: fontawesome/brands/discord 
  #     link: https://fosstodon.org/@squidfunk
  #   - icon: fontawesome/brands/github 
  #     link: https://fosstodon.org/@squidfunk
  #   - icon: fontawesome/brands/docker
  #     link: https://fosstodon.org/@squidfunk

